<?php

/**
 * @file
 * Hooks for block_access_records module.
 */

use Drupal\block\BlockInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_block_update().
 *
 * Update the access records when a block is saved.
 */
function block_access_records_block_update(BlockInterface $block) {
  \Drupal::service('block.repository.access_records')->updateAccessRecords($block);
}

/**
 * Implements hook_block_insert().
 *
 * Update the access records when a block is saved.
 */
function block_access_records_block_insert(BlockInterface $block) {
  \Drupal::service('block.repository.access_records')->updateAccessRecords($block);
}

/**
 * Implements hook_block_delete().
 *
 * Update the access records when a block is deleted.
 */
function block_access_records_block_delete(BlockInterface $block) {
  \Drupal::service('block.repository.access_records')->updateAccessRecords($block, TRUE);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function block_access_records_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('block.repository.access_records')->alterForm($form, $form_state, $form_id);
}
